# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Programmierung
email: tiwarisachin147@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Get all the know-hows of programming right here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sachin147.github.io" # the base hostname & protocol for your site
twitter_username: sachin7RT
github_username:  sachin147

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman